### ISSUE TITLE
Update species list

### ISSUE THREAD

**Issue by pgmccann** [StAResComp/peru-fish#17]

**Comment by taniamendo** [comment]
tania: need the species list!

**Comment by taniamendo** [comment]
List of species for "fish 1 form row" to be added as a table.

Merluza
Cabrilla
Doncella
Falso volador
Peje
Bereche
Diablico
Cachema
Raya
Chiri
Tollo

**Comment by pgmccann** [comment]
Present list of 10 species for each row, against each of which the user enters a weight
